# Hexo Configuration ç«™ç‚¹é…ç½®æ–‡ä»¶
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site ç½‘ç«™é…ç½®
# ç½‘ç«™æ ‡é¢˜
title: poppyJ's Blog
# ç½‘ç«™å‰¯æ ‡é¢˜
subtitle: 
# ç½‘ç«™æè¿°
description: 2019 åŠªåŠ›å˜æˆæ›´å¥½çš„è‡ªå·± ğŸ’ª
keywords:
# æ˜µç§°, ç”¨äºä¸»é¢˜æ˜¾ç¤ºæ–‡ç« çš„ä½œè€…
author: poppyJ
# ç½‘ç«™ä½¿ç”¨çš„è¯­è¨€(è‹±æ–‡:en, ç®€ä½“ä¸­æ–‡:zh-Hansï¼Œç¹ä½“ä¸­æ–‡:zh-twï¼ŒNext ä¸»é¢˜ä½¿ç”¨:zh-CN)
language: zh-CN
# ç½‘ç«™æ—¶åŒºï¼Œç”¨äºç”Ÿæˆé¡µé¢æ—¶å¡«å……ç›¸å…³æ—¶é—´ï¼Œé»˜è®¤ä½¿ç”¨ç”µè„‘æ—¶åŒºï¼Œä¸€èˆ¬ä¸ç”¨æ”¹
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# ç«™ç‚¹ç½‘å€
url: https://poppyj.github.io/
# ç½‘ç«™æ ¹ç›®å½•
root: /
# æ–‡ç« çš„æ°¸ä¹…é“¾æ¥æ ¼å¼
# permalink: :year/:month/:day/:title/
permalink: :title/

# æ°¸ä¹…é“¾æ¥ä¸­å„éƒ¨åˆ†çš„é»˜è®¤å€¼
permalink_defaults:

# Directory ç›®å½•
# èµ„æºæ–‡ä»¶å¤¹ï¼Œè¿™ä¸ªæ–‡ä»¶å¤¹ç”¨æ¥å­˜æ”¾åšå®¢å†…å®¹
source_dir: source
# å…¬å…±æ–‡ä»¶å¤¹ï¼Œè¿™ä¸ªæ–‡ä»¶å¤¹ç”¨æ¥å­˜æ”¾ç”Ÿæˆçš„ç«™ç‚¹é™æ€æ–‡ä»¶
public_dir: public
# æ ‡ç­¾æ–‡ä»¶å¤¹
tag_dir: tags
# å½’æ¡£æ–‡ä»¶å¤¹
archive_dir: archives
# åˆ†ç±»æ–‡ä»¶å¤¹
category_dir: categories
# Include codeæ–‡ä»¶å¤¹
code_dir: downloads/code
# å›½é™…åŒ–æ–‡ä»¶å¤¹ï¼Œå­˜æ”¾å„ç§è¯­è¨€å®šä¹‰
i18n_dir: :lang
# è·³è¿‡æŒ‡å®šæ–‡ä»¶çš„æ¸²æŸ“
skip_render:

# Writing
# æ–°æ–‡ç« çš„æ–‡ä»¶åç§°
new_post_name: :title.md # File name of new posts
# é¢„è®¾å¸ƒå±€
default_layout: post
# åœ¨ä¸­æ–‡å’Œè‹±æ–‡ä¹‹é—´åŠ å…¥ç©ºæ ¼
auto_spacing: true
# æŠŠæ ‡é¢˜è½¬æ¢ä¸º title case
titlecase: false # Transform title into titlecase
# åœ¨æ–°æ ‡ç­¾ä¸­æ‰“å¼€é“¾æ¥
external_link: true # Open external links in new tab
# æŠŠæ–‡ä»¶åç§°è½¬æ¢ä¸º (1) å°å†™æˆ– (2) å¤§å†™
filename_case: 0
# æ˜¾ç¤ºè‰ç¨¿
render_drafts: false
# å¼€å¯æ–‡ç« èµ„æºæ–‡ä»¶å¤¹
post_asset_folder: true
# æŠŠé“¾æ¥æ”¹ä¸ºä¸æ ¹ç›®å½•çš„ç›¸å¯¹ä½å€
relative_link: false
# æ˜¾ç¤ºæœªæ¥çš„æ–‡ç« 
future: true
# è§£å†³è‹±æ–‡å¼•å·åŠè§’å˜å…¨è§’
marked:
  smartypants: false
# ä»£ç å—çš„è®¾ç½®
highlight:
  enable: true
  line_number: true
  # ä»£ç è‡ªåŠ¨é«˜äº®
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag åˆ†ç±» & æ ‡ç­¾
# é»˜è®¤åˆ†ç±»
default_category: uncategorized
# åˆ†ç±»åˆ«å
category_map:
# æ ‡ç­¾åˆ«å
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
# Hexo ä½¿ç”¨ Moment.js æ¥è§£æå’Œæ˜¾ç¤ºæ—¶é—´
# æ—¥æœŸæ ¼å¼
date_format: YYYY-MM-DD
# æ—¶é—´æ ¼å¼
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
# æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« é‡ (0 = å…³é—­åˆ†é¡µåŠŸèƒ½)
per_page: 10
pagination_dir: page

# Extensions æ‰©å±•
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# ä¸»é¢˜
theme: next

# Deployment éƒ¨ç½²
## Docs: https://hexo.io/docs/deployment.html
# è¿™é‡Œä½¿ç”¨ Travis CI åšå®¢ç®¡ç†è‡ªåŠ¨éƒ¨ç½² source åˆ†æ”¯åˆ° master
## Docs: https://liolok.github.io/Hexo-Travis-CI/
deploy:
- type: git
  repo: git@github.com:poppyJ/poppyJ.github.io.git
  branch: master
- type: git
  repo: git@git.dev.tencent.com:poppyJ/poppyJ.git
  branch: master
  # other deployer
- type: leancloud_counter_security_sync

# Local Search è‡ªå®šä¹‰ç«™ç‚¹å†…å®¹æœç´¢
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# leancloud å®‰å…¨è®¾ç½®
leancloud_counter_security:
  enable_sync: true
  app_id: swYleTTBfYTvzUbgkoY9AjUY-gzGzoHsz
  app_key: 8OKz6eRv6gqGWEyUoxUBiDWw
  username: 2392805553
  password: 1340692282Jin

# æ–‡ç« å­—æ•°ç»Ÿè®¡
symbols_count_time:
  # æ–‡ç« å†…æ˜¯å¦æ˜¾ç¤º
  symbols: true
  time: true
  # ç½‘é¡µåº•éƒ¨æ˜¯å¦æ˜¾ç¤º
  total_symbols: true
  total_time: true